import Head from 'next/head'
import React from 'react'
import styles from '../styles/About.module.css'

export default function About() {
  return (
    <div>
      <Head>
        <title>irys:about</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <h1>About the Team</h1>
      </div>
    </div>
  )
}
