import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Irys</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className={styles.top}>
          <div className={styles.titleBox}>
            <h1>
              IRYS
            </h1>
            <p>
              Et porttitor praesent viverra ut enim enim dui.
            </p>
            <button className={styles.openAppButton}>OPEN APP</button>
          </div>
          <img className={styles.hero} src="/heroWaves.svg"></img>
        </div>


        <div className={styles.middle}>

        </div>

        <div className={styles.bottom}>
          <div className={styles.bottomText}>
            <h1>Technology</h1>
            <p>
              Congue quisque consectetur lectus scelerisque urna rutrum ut venenatis nib.
              Pellentesque interdum semper dolor morbi libero. Mollis placerat viverra scelerisque viverra magna. Turpis faucibus sodales arcu dui amet, pellentesque vitae eget euismod. Viverra interdum sed placerat proin in. Tellus turpis placerat nunc egestas facilisi. Egestas vel turpis mauris est. Fermentum sem massa morbi in volutpat.
            </p>
            <li className="techStack">
              <img src="/nvidia.svg" alt='nvidia' />
              <img src="/nextjs.svg" alt='nextjs' />
              <img src="/cockroachlabs.svg" alt='cockroachlabs' />
              <img src="/opencv.svg" alt='opencv' />
            </li>
          </div>

          <div className={styles.footer}></div>
        </div>

      </div>


    </div >
  )
}

export default Home
