import axios from 'axios'
import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { forwardRef } from 'react'
import styles from '../styles/Home.module.css'


const callPython = () => {
  axios.get(
    'http://localhost:8080'
  ).then((res) => {
    console.log(res.data);
  });
}

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Irys</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className={styles.top}>
          <div className={styles.titleBox}>
            <h1>
              IRYS
            </h1>
            <p>
              Et porttitor praesent viverra ut enim enim dui.
            </p>
            <button
              onClick={() => callPython()}
              className={styles.openAppButton}
            >OPEN APP</button>
          </div>
          <img className={styles.hero} src="/heroWaves.svg"></img>
        </div>


        <div id="middle" className={styles.middle}>
          <div>
            <img src="/laptop.svg" alt="" />
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id urna dolor ut vestibulum mauris. Velit odio facilisis lobortis viverra convallis nisl volutpat. Orci aliquet nec diam quam. Cursus turpis gravida sed ultricies quis duis cras lectus sed.</p>
          </div>
          <div>
            <img src="/eye.svg" alt="" />
            <p>Scelerisque at sit velit et, eget in augue consectetur. Tortor, neque, sollicitudin nisl consectetur duis. Dolor, mi purus hendrerit ultricies purus. Eget scelerisque orci proin pellentesque aenean. Sed sed in risus aliquet id.</p>
          </div>
          <div>
            <img src="/handshake.svg" alt="" />
            <p>Nisl, at dui arcu facilisis. Quis hendrerit suspendisse purus viverra eget gravida ut. Risus facilisi magna tortor, eget senectus semper. Velit a non faucibus porttitor phasellus ac.</p>
          </div>
        </div>

        <div id="bottom" className={styles.bottom}>
          <div className={styles.bottomText}>
            <h1>Technology</h1>
            <p>
              Congue quisque consectetur lectus scelerisque urna rutrum ut venenatis nib.
              Pellentesque interdum semper dolor morbi libero. Mollis placerat viverra scelerisque viverra magna. Turpis faucibus sodales arcu dui amet, pellentesque vitae eget euismod. Viverra interdum sed placerat proin in. Tellus turpis placerat nunc egestas facilisi. Egestas vel turpis mauris est. Fermentum sem massa morbi in volutpat.
            </p>

            <img className={styles.first} src="/python.svg" alt='python' />
            <img className={styles.second} src="/nextjs.svg" alt='nextjs' />
            <img className={styles.third} src="/cockroachlabs.svg" alt='cockroachlabs' />
            <img className={styles.fourth} src="/opencv.svg" alt='opencv' />
          </div>

          <div className={styles.footer}></div>
        </div>

      </div>


    </div >
  )
}

export default Home
