import Head from 'next/head'
import React from 'react'
import styles from '../styles/About.module.css'

export default function team() {
  return (
    <div>
      <Head>
        <title>irys:team</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <div className={styles.text}>
          <h1>The Team</h1>
          <ul className={styles.list}>
            <li>Griffin Ogura: FrontEnd Dev</li>
            <li>Jay Katyan: Backend Dev</li>
            <li>Rakesh Pillai: Backend Dev</li>
            <li>Rahul Ramakrishnan: Technical Writer</li>
          </ul>
        </div>
        <div className={styles.waves}></div>
      </div>
    </div>
  )
}
